#!/usr/bin/with-contenv bash

if ! dpkg -l | grep python3-dev > /dev/null; then
    echo "**** Adding python3 to package install list ****"
    echo "\
        build-essential \
        libssl-dev \
        libffi-dev \
        python3.10-dev \
        python3.10-pip \
        python3.10-venv \
        python3.10" >> /mod-repo-packages-to-install.list
else
    echo "**** python3 already installed ****"
fi
