#!/usr/bin/with-contenv bash

echo "**** installing python3 dev environment ****"
apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3.10-dev \
    python3.10-pip \
    python3.10-venv \
    python3.10
